# Generated by Django 5.1 on 2024-09-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Время запроса')),
                ('remote_ip', models.CharField(max_length=255, verbose_name='IP адрес')),
                ('remote_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('http_method', models.CharField(max_length=255, verbose_name='HTTP метод')),
                ('response', models.IntegerField(verbose_name='Код ответа HTTP')),
                ('bytes', models.IntegerField(verbose_name='Размер ответа в байтах')),
                ('referrer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Реферер')),
                ('agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
